CREATE TABLE [dbo].[Staff]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [FirstName] NVARCHAR(100) NOT NULL, 
    [LastName] NVARCHAR(100) NULL, 
    [UserName] VARCHAR(100) NOT NULL UNIQUE, 
    [Password] VARCHAR(128) NOT NULL UNIQUE, 
    [EMail] VARCHAR(100) NULL, 
    [AccessLevel] TINYINT NOT NULL
)
